"""followers feature added

Revision ID: 167306d8c85c
Revises: 5f9b5c199dd2
Create Date: 2021-09-15 08:58:29.408567

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '167306d8c85c'
down_revision = '5f9b5c199dd2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
